### ISSUE TITLE
training not seemed to be working?

### ISSUE THREAD

**Issue by MrThiago** [hardikbansal/Qlearning#2]
I cab see the game.
But it keeps on repeating sane steps:

Total rewards in episode 73 is 3.799999999999999 total number of steps are 3626
Total rewards in episode 74 is 3.799999999999999 total number of steps are 3675
Total rewards in episode 75 is 3.799999999999999 total number of steps are 3724
Total rewards in episode 76 is 3.799999999999999 total number of steps are 3773
Total rewards in episode 77 is 3.799999999999999 total number of steps are 3822
Total rewards in episode 78 is 3.799999999999999 total number of steps are 3871
Total rewards in episode 79 is 3.799999999999999 total number of steps are 3920
Total rewards in episode 80 is 3.799999999999999 total number of steps are 3969
Total rewards in episode 81 is 3.799999999999999 total number of steps are 4018
Total rewards in episode 82 is 3.799999999999999 total number of steps are 4067
Total rewards in episode 83 is 3.799999999999999 total number of steps are 4116
Total rewards in episode 84 is 3.799999999999999 total number of steps are 4165
Total rewards in episode 85 is 3.799999999999999 total number of steps are 4214
Total rewards in episode 86 is 3.799999999999999 total number of steps are 4263
Total rewards in episode 87 is 3.799999999999999 total number of steps are 4312
Total rewards in episode 88 is 3.799999999999999 total number of steps are 4361
Total rewards in episode 89 is 3.799999999999999 total number of steps are 4410
Total rewards in episode 90 is 3.799999999999999 total number of steps are 4459
Total rewards in episode 91 is 3.799999999999999 total number of steps are 4508
Total rewards in episode 92 is 3.799999999999999 total number of steps are 4557
Total rewards in episode 93 is 3.799999999999999 total number of steps are 4606
Total rewards in episode 94 is 3.799999999999999 total number of steps are 4655
Total rewards in episode 95 is 3.799999999999999 total number of steps are 4704
Total rewards in episode 96 is 3.799999999999999 total number of steps are 4753
Total rewards in episode 97 is 3.799999999999999 total number of steps are 4802
Total rewards in episode 98 is 3.799999999999999 total number of steps are 4851
Total rewards in episode 99 is 3.799999999999999 total number of steps are 4900
Total rewards in episode 100 is 3.799999999999999 total number of steps are 4949
Total rewards in episode 101 is 3.799999999999999 total number of steps are 4998
Total rewards in episode 102 is 3.799999999999999 total number of steps are 5047
Total rewards in episode 103 is 3.799999999999999 total number of steps are 5096
Total rewards in episode 104 is 3.799999999999999 total number of steps are 5145
Total rewards in episode 105 is 3.799999999999999 total number of steps are 5194
Total rewards in episode 106 is 3.799999999999999 total number of steps are 5243

it is not improving.
is there anything else we need to do ?

Thanks

**Comment by hardikbansal** [comment]
For starting 10000 steps I will be taking random steps. It will take more than million steps to get some significant results. I will suggest to use GPU machine to train this network.

**Comment by MrThiago** [comment]
ok. thank you
